### ISSUE TITLE
I am not able to use the npm run dist: win accompanies this error

### ISSUE THREAD

**Issue by MatheusMoreira0101** [haxzie/instagram-live-streamer#1]
![image](https://user-images.githubusercontent.com/54282051/79075973-a9abc280-7ccc-11ea-8fae-fa9fc149f947.png)

**Comment by gvasilakiss** [comment]
I have the same issue too.

**Comment by MatheusMoreira0101** [comment]
I went to package.json and in scripts I changed what was at start to "start": "react-scripts start", and so at least npm start is back up and running

**Comment by gvasilakiss** [comment]
![image](https://user-images.githubusercontent.com/34243942/79506367-81aabf00-803e-11ea-9e2e-327521502f2e.png)

Like this?

Because I'm still getting the same error.

**Comment by MatheusMoreira0101** [comment]
uses npm start

**Comment by haxzie** [comment]
Thanks for reporting @MatheusMoreira0101 @gvasilakiss, I have fixed the issue with `npm run dist:win` on windows machines in the latest update. Feel free to test it out and let me know if the issue still persists.

**Comment by gvasilakiss** [comment]
Hey there, now when I run the program I get this 
![image](https://user-images.githubusercontent.com/34243942/79569742-de4ebe00-80c0-11ea-8f66-ad60524dc851.png)

**Comment by haxzie** [comment]
Hey @gvasilakiss, I have tested this on a windows machine. Couldn't reproduce it. Can you let me know the commands you have used to start the application?

Ideally the following command should work on windows.
```
npm run electron-dev
```
If you get an error saying `'BROWSER' is not recognized`, just remove `BROWSER=none` from the `electron-dev` run script in package.json

**Comment by gvasilakiss** [comment]
To start the application I do:

`npm run dist:win`

Is this the correct format?

![image](https://user-images.githubusercontent.com/34243942/79575255-2c1bf400-80ca-11ea-912f-d706c9574dd8.png)

**Comment by haxzie** [comment]
I have pushed a hot-fix to change a few things in the run scripts. Please pull the changes and try again.

**Comment by haxzie** [comment]
`npm run dist:win` is used to create production builds of the app. To run the app in development mode `npm run electron-dev` is used.

**Comment by gvasilakiss** [comment]
This is the message I get now:
![image](https://user-images.githubusercontent.com/34243942/79576051-5b7f3080-80cb-11ea-81da-94d98ee2f053.png)

I tried the cross-env but I didn't work.

**Comment by haxzie** [comment]
`cross-env` is a development dependency, you might need to run `npm install`

**Comment by gvasilakiss** [comment]
Okay now its working form the electro-dev

**Comment by gvasilakiss** [comment]
When I'm trying to log in I get this now:
`:3000/#/:1 Form submission cancelled because the form is not connected`

**Comment by haxzie** [comment]
Try, pulling the latest changes :smile: I have encountered this and sent a fix.

**Comment by gvasilakiss** [comment]
I pulled the latest one, but still the same issue

**Comment by haxzie** [comment]
Cross-platform development is a pain :face_with_head_bandage: . I'll take a close look. into this one Do check if the problem exists on production builds.:)

**Comment by gvasilakiss** [comment]
Okay, will wait for your reply.

**Comment by MatheusMoreira0101** [comment]
When I login it returns to the terminal

 (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

![image](https://user-images.githubusercontent.com/54282051/79581664-24942500-80a1-11ea-92e4-85c81e9493df.png)

**Comment by mukmin-rockman** [comment]
alhamdulillah, but I can't save 24 hours 😄 , 
![clear](https://user-images.githubusercontent.com/64290798/80265193-f7f39500-86c0-11ea-895d-443ad70a14fb.png)

**Comment by haxzie** [comment]
@mukmin-rockman Option will be available in the upcoming release 👍🏼

**Comment by mukmin-rockman** [comment]
Thank you very much (Jazakallahu khairan) Mr. @haxzie 👍

**Comment by gvasilakiss** [comment]
> alhamdulillah, but I can't save 24 hours 😄 ,
> ![clear](https://user-images.githubusercontent.com/64290798/80265193-f7f39500-86c0-11ea-895d-443ad70a14fb.png)

How you managed to get it working?

Can you send the steps you followed, I did what was said in the readme file, but no luck.

**Comment by dhanushp** [comment]
> When I login it returns to the terminal
> 
> (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false". It will change to be "true" in Electron 9. For more information please check [electron/electron#18397](https://github.com/electron/electron/issues/18397)
> 
> ![image](https://user-images.githubusercontent.com/54282051/79581664-24942500-80a1-11ea-92e4-85c81e9493df.png)

Even I had the same issue. The latest update has helped me fix it. Please do check it. kudos @haxzie

**Comment by mukmin-rockman** [comment]
![WhatsApp Image 2020-05-04 at 16 51 05](https://user-images.githubusercontent.com/64290798/80954892-75897480-8e28-11ea-8ef5-1df80247f3ca.jpeg) the video was automatically saved, I'm waiting for the next update

**Comment by mukmin-rockman** [comment]
chat me via Whatapps +62 85701113692

**Comment by monillosagasta** [comment]
can i live with others in obs ?

**Comment by haxzie** [comment]
@monillosagasta As of now, nope.
