### ISSUE TITLE
[BUG] Unbale to get past instagram verification checkpoint

### ISSUE THREAD

**Issue by osyduck** [haxzie/instagram-live-streamer#13]
I got infinity checkpoint, I've clicked "this was me" but when I start to login, it happened again. Please add verify method by phone or email

**Comment by haxzie** [comment]
Thanks for opening the issue @osyduck . This seems like a known issue among a few other users. I'm investigating this issue right now, will update here once I can find any fix. :+1:

**Comment by osyduck** [comment]
Maybe you can look at https://instafeed.me/rtmp/ ... they add verify method when we get checkpoint

**Comment by haxzie** [comment]
Fix for 2FA and Checkpoints will be released in coming few days ✨

**Comment by osyduck** [comment]
Nice works dude
