### ISSUE TITLE
[FEAT] Feature Requests

### ISSUE THREAD

**Issue by osyduck** [haxzie/instagram-live-streamer#17]
### Would be wonderful if this app can

1. Pin & Unpin a comment.
2. Wave to user.
3. Input video from youtube to ig (ffmpeg).
4. Add option to save live video to story or discard in the end of stream.
5. Accept, reject and close requests to being part of a live is accessible from this app.

**Comment by haxzie** [comment]
Awesome! thanks for the suggestions @osyduck 
> 5. Accept, reject and close requests to being part of a live is accessible from this app.

This would be useful only if there is someway to actually see the other person through the app. Currently the only way to actually see our own stream and comments from a viewers perspective is to go to `https://instagram.com/YOURUSERNAME/live`. What do you think?

**Comment by osyduck** [comment]
Maybe, but I couldn't find this endpoint on instagram-private-api repository. Could you find that?

**Comment by haxzie** [comment]
I couldn't find that too.. anyway recreating more of instagram's functionality is not a good idea. It might also be illegal according to their ToS.
