### ISSUE TITLE
do not perform the login and the cors error

### ISSUE THREAD

**Issue by MatheusMoreira0101** [haxzie/instagram-live-streamer#2]
![image](https://user-images.githubusercontent.com/54282051/79088989-c66ee700-7d1a-11ea-951c-faf9109fea3a.png)

**Comment by haxzie** [comment]
Hey @MatheusMoreira0101, Can you help me with more details?
- Operating system
- Commands you ran to start the app

**Comment by MatheusMoreira0101** [comment]
Cross-origin request blocked: The same origin policy (Same Origin Policy) prevents the remote resource from being read at https://i.instagram.com/api/v1/qe/sync/. (Reason: the ‘user-agent’ header is not allowed according to the ‘Access-Control-Allow-Headers’ header of the CORS verification response)
