### ISSUE TITLE
Samsung SM-G965F

### ISSUE THREAD

**Issue by hamzahbatha** [haxzie/instagram-live-streamer#43]
I got a message saying there was a login through a Samsung SM-G965F. Is this normal. Do you run a virtual machine (something like BlueStacks) in order to stream to Instagram?

**Comment by haxzie** [comment]
Internally we do use a device Id to communicate with Instagram APIs, so it's common to recieve an email from Instagram about the login. But most of the time it should be a Xiaomi MI device. So, if you feel like something is not right, please change your password immediately. The app only communicates your credentials to Instagram and it's not stored anywhere else other than your PC. Make sure the mail you recieved have the correct geo location mentioned as your current location, if not please change your credentials.

**Comment by hamzahbatha** [comment]
Oh ok thanks for letting me know! The location and time seems to be accurate from when I signed into it. I was just a little startled when I saw the device model since I don’t own that one..
