### ISSUE TITLE
4 hour feature is not working

### ISSUE THREAD

**Issue by jb95bussiness** [haxzie/instagram-live-streamer#46]
Hi
thanks for the wonderful app
unfortunately with the new version of the app, after one hour instagram live stops but the timer countdown inside the app continues
so after all the 4 hour feature of your app with the latest instagram update is not working
it would be great to fix it
thanks

**Comment by guimatheus01** [comment]
Hello, I have this bug too, Streamon marks 4 hours, but in 1 hour OBS loses connection, the key has expired, but Streamon continues to count as if the transmission was still running, but OBS is setting 0 bitrate. I am using it to broadcast church meetings and usually the meetings last more than 1 hour, I think this correction would already help many others who use it for other purposes as well. I'm using the Linux version of Streamon, in the PopOS_20.04 distribution.

**Comment by haxzie** [comment]
@jb95bussiness @guimatheus01 This is an issue with Instagram having limits set to accounts. Not all accounts can stream for 4 hours, some accounts have this limit set to 1 hour. Streamon assumes every account to have 4 hour stream limit. We will add checks to make sure we show hours depending upon the user's profile :+1:
