### ISSUE TITLE
Build and Installation successful but blank screen after launching

### ISSUE THREAD

**Issue by ayushd03** [haxzie/instagram-live-streamer#7]
I followed the instructions as mentioned. I made sure NPM, node and python were updated before beginning. Build was successful and I was able to install it without any errors. But after launching the application from command line I just get a blank screen. I tried to run it in development mode and tried to access localhost:3000 but it too just opens a blank page with the header Instagram Live Streamer but doesnt show any content. I tried it on Kali as well as Parrot OS and got the same output. Is there anything that I am missing ?

![image](https://user-images.githubusercontent.com/28046229/79737515-0b95a900-8319-11ea-800c-8cf4cc4fd748.png)

**Comment by ahangarha** [comment]
I get the same issue if I run `npm run start` and also if I run AppImage on my Gnu/Linux machine.

thought running with npm `npm run electron-dev` worked fine

**Comment by ahangarha** [comment]
should I open a new issue?

**Comment by haxzie** [comment]
Hey @ahangarha, the commands `npm run start` won't show any results since it just runs the react server. The `npm run electron-dev` makes sure both the electron and react app is running together. If you are facing any issues while using the command, or while running `npm run dist:linux` take a closer look at the logs and let me know if you find any errors.

**Comment by ahangarha** [comment]
the Build process finishes with no error:
```
npm run dist:linux 

> instagram-live-streamer@0.1.0 dist:linux /home/PATH/instagram-live-streamer-js
> electron-builder --linux

  • electron-builder  version=22.4.1 os=5.3.0-46-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=node-sass@4.13.1 platform=linux arch=x64
  • packaging       platform=linux arch=x64 electron=8.0.3 appOutDir=dist/linux-unpacked
  • building        target=AppImage arch=x64 file=dist/instagram-live-streamer-0.1.0.AppImage
  • default Electron icon is used  reason=application icon is not set
  • building        target=deb arch=x64 file=dist/instagram-live-streamer_0.1.0_amd64.deb
```
