### ISSUE TITLE
What is the license

### ISSUE THREAD

**Issue by ahangarha** [haxzie/instagram-live-streamer#8]
I didn't find any license info in the repository. What is the license of this app?

**Comment by haxzie** [comment]
Hey @ahangarha, sorry for the delay. The API (library) used in the project uses MIT and this project is licensed under the same. But keep in mind about the names and logos of Instagram, we will be removing them shortly. If you are planning to fork, further build or distribute please note to remove any and all branding of Instagram from the code base.

**Comment by ahangarha** [comment]
I wanted to use it for myself. but regarding your point regarding logo, check this quick design:

![insta-stream-test01](https://user-images.githubusercontent.com/11241315/80231988-6a388b00-8669-11ea-9423-6e1b41d06dec.png)

**Comment by haxzie** [comment]
@ahangarha Thank you for the suggestion. We are planning to take forward the development of this app by including more streaming options to multiple networks soon, the logo and branding of the app will be decided based on that in near future.
