### ISSUE TITLE
[BUG] Blank application on Linux Mint 19.3 Xfce

### ISSUE THREAD

**Issue by elmunats** [haxzie/instagram-live-streamer#9]
Image :
https://serving.photos.photobox.com/298734121c2c71d54ca821248745eb0014b5f4be1f906179e7b89c2e0a21fb271f5669cc.jpg

**Comment by haxzie** [comment]
Hey @elmunats Thanks for opening the issue. I need a bit more info about the commands you have ran to run the application.

**Comment by knro** [comment]
Same here on Ubuntu 18.04 using latest git code.

```
external "events":1 Uncaught ReferenceError: require is not defined
    at Object.events (external "events":1)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Object../node_modules/webpack/hot/emitter.js (emitter.js:1)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Object../node_modules/webpack/hot/dev-server.js (dev-server.js:50)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Object.1 (global.scss?6d54:45)
```

**Comment by haxzie** [comment]
Hey @knro can you post the commands you used to run the application?

**Comment by knro** [comment]
The exact ones listed on the Github page. I first went via that route and install the Debian package on 18.04 and when I started it I got blank. Then I just went ahead to the instagram-live-streamer directory and type **npm start** and got this:

```
Compiled with warnings.

./src/Pages/Home/index.jsx
  Line 122:9:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

./src/components/Toggle/index.jsx
  Line 2:8:  'styles' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

```

It opened a tab in Chrome and when I checked the console logs, I found the issue I reported above. I tried to see if it is some electron issue but it appears that npmIntegration is already set to true in electron.js

**Comment by haxzie** [comment]
@knro instead of `npm start` try `npm run electron dev`

**Comment by knro** [comment]
That works! and I can login as well. I haven't yet tested the live stream, but it's looking good!

**Comment by knro** [comment]
The live stream worked, though the comments were disabled and I had to toggle a few times on/off to get it work. There is no way to watch the comments from the app?

**Comment by haxzie** [comment]
There is a known bug with the comments switch. Viewing comments are not supported as of now. Hopefully in future releases we you will be able to view and add comments :+1:

**Comment by elmunats** [comment]
> Hey @elmunats Thanks for opening the issue. I need a bit more info about the commands you have ran to run the application.

thank you very much, it has been working well on linux mint.
